### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by ryanpcmcquen** [cfdrake/standardnotes-todo-editor#15]
Standard Notes gives the following error when trying to install the todo editor.
```
Unable to register this extension. Make sure the link is valid and try again.
```
![screenshot 2017-05-28 at 10 49 08](https://cloud.githubusercontent.com/assets/772937/26530904/6ab686fc-4393-11e7-8b27-4ad5404db5bc.png)

**Comment by mobitar** [comment]
Try this:
https://cfdrake.github.io/standardnotes-todo-editor/?name=Todos&type=editor
